from doc_topic_coh.evaluations.scorer_build_data import DocCoherenceScorer, scorersFromParams
from doc_topic_coh.evaluations.tools import topicMeasureAuc, \
    flattenParams as fp, joinParams as jp
from doc_topic_coh.dataset.topic_splits import devTestSplit2
from pytopia.measure.topic_distance import cosine, l1, l2
from doc_topic_coh.evaluations.experiment import IdDict, IdList, \
    TopicScoringExperiment as TSE

def distanceLdaSpread():
    p = [
        {'distance': l2, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'variance'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': l2, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'variance'},
        {'distance': l2, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'variance'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'variance'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'variance'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100, 'type': 'variance'},
        {'distance': l2, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'variance'},
        {'distance': l2, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'variance'},
        {'distance': l2, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'avg-dist'},
        {'distance': l2, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'variance'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'variance'},
        {'distance': l2, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'variance'},
        {'distance': l2, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100, 'type': 'variance'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'variance'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'variance'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100, 'type': 'variance'},
        {'distance': l2, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'variance'},
        {'distance': l2, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 25, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 25, 'type': 'variance'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'variance'},
        {'distance': l2, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 25, 'type': 'variance'},
        {'distance': l2, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 25, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 25, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'variance'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'variance'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 25, 'type': 'variance'},
        {'distance': l2, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': l2, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': l2, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 25, 'type': 'variance'},
        {'distance': l2, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 25, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'variance'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 25, 'type': 'variance'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100,
         'type': 'variance'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100,
         'type': 'variance'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 25, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 25, 'type': 'variance'},
        {'distance': l1, 'center': 'mean', 'vectors': 'models1', 'exp': 1.0, 'threshold': 25, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 25, 'type': 'variance'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 25, 'type': 'variance'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 50, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 100,
         'type': 'avg-dist'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100,
         'type': 'avg-dist'},
        {'distance': cosine, 'center': 'mean', 'vectors': 'models1', 'exp': 2.0, 'threshold': 100, 'type': 'variance'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 25, 'type': 'avg-dist'},
        {'distance': l1, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 25, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 1.0, 'threshold': 25, 'type': 'avg-dist'},
        {'distance': cosine, 'center': 'median', 'vectors': 'models1', 'exp': 2.0, 'threshold': 25, 'type': 'avg-dist'},
    ]
    #p = p[:20]
    p = IdList(p); p.id = 'dist_lda_spread'
    return p

def graphCorpusSpread():
    p = [
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.84746], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.84746], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.84746], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 1.84746], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 100, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 100, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 100, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 100, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 100, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 100, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.84746], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.84746], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.35688], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 1.84746], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.98525], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.96886], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 100, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 100, 'weightFilter': [0, 1.84746], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 100, 'weightFilter': [0, 1.84746], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.98635], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.98925], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.98925], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 100, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 100, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.98925], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.98925], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 50, 'weightFilter': [0, 1.98925], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.95097], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.37364], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.90951], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 1.98925], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.97251], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.92783], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': None, 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 50, 'weightFilter': None, 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.3946], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.94344], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.87706], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.99536], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.38319], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.95661], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.88496], 'type': 'graph'},
        {'distance': l1, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 1.94139], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': cosine, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.99478], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.41052], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'closeness', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.23936], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 0.97246], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.23936], 'type': 'graph'},
        {'distance': l1, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 1.98925], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.23936], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'mean', 'algorithm': 'communicability', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.23936], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': l2, 'weighted': False, 'center': 'median', 'algorithm': 'communicability',
         'vectors': 'probability', 'threshold': 25, 'weightFilter': [0, 0.23936], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'median', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 25, 'weightFilter': [0, 0.92056], 'type': 'graph'},
        {'distance': l2, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'tf-idf',
         'threshold': 50, 'weightFilter': [0, 1.40374], 'type': 'graph'},
        {'distance': cosine, 'weighted': True, 'center': 'mean', 'algorithm': 'clustering', 'vectors': 'probability',
         'threshold': 25, 'weightFilter': [0, 0.87706], 'type': 'graph'},
    ]
    p = p[:100]
    p = IdList(p); p.id = 'graph_corpus_spread'
    return p

def experiment(params, action='run', dataset='dev', confInt=False):
    dev, test = devTestSplit2()
    expFolder = '/datafast/doc_topic_coherence/experiments/iter4_coherence/'
    if dataset == 'dev': topics = dev
    else: topics = test
    print params.id
    print 'num params', len(params)
    tse = TSE(paramSet=params, scorerBuilder=DocCoherenceScorer,
              ltopics=topics, posClass=['theme', 'theme_noise'],
              folder=expFolder, cache=True)
    if action == 'run': tse.run()
    elif action == 'print': tse.printResults(confInt=confInt)
    elif action == 'signif': tse.significance(threshold=0.05)
    else: print 'specified action not defined'

def plotSpreads():
    pass

if __name__ == '__main__':
    experiment(distanceLdaSpread(), 'run', 'test')
    #experiment(graphCorpusSpread(), 'run', 'test', confInt=True)